n = int(input('Digite um número:'))
z = n*int(0)
p = n*int(1)
s = n*int(2)
t = n*int(3)
q = n*int(4)
qui = n*int(5)
sex = n*int(6)
set = n*int(7)
o = n*int(8)
nono = n*int(9)
d = n*int(10)
print('A tabuada do número {} é: \n {} x 0 = {} \n {} x 1 = {} \n {} x 2 = {} \n {} x 3 = {} \n {} x 4 = {} \n {} x 5 = {} \n {} x 6 = {} \n {} x 7 = {} \n {} x 8 = {} \n {} x 9 = {} \n {} x 10 = {}'.format(n, n, z, n, p, n, s, n, t, n, q, n, qui, n, sex, n, set, n, o, n, nono, n, d))
